# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: OpenTimelineIO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,]
        python-version: [2.7, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cibuildwheel
      run: |
          python -m pip install cibuildwheel==1.6.4
          
    - name: Install Visual C++ for Python 2.7
      if: runner.os == 'Windows'
      run: |
          choco install vcpython27 -f -y
          
    - name: Build wheels
      env:
        CIBW_ENVIRONMENT: "OTIO_CXX_COVERAGE_BUILD = 1"
        CIBW_TEST_COMMAND: pytest ./tests
      run: |
          python -m cibuildwheel --output-dir wheelhouse
